Goblin:
  path_to_image: "enemies/src/goblin"
  velocity: 10
  health: 100
  damage: 5
  scale: [0.1, 0.13]
  score: 5

Archfiend:
  path_to_image: "enemies/src/archfiend"
  velocity: 13
  health: 350
  damage: 90
  scale: [0.09, 0.16]
  score: 61

Imp:
  path_to_image: "enemies/src/imp"
  velocity: 19
  health: 100
  damage: 5
  scale: [0.09, 0.15]
  score: 5

Floatingeye:
  path_to_image: "enemies/src/floatingeye"
  velocity: 5
  health: 500
  damage: 100
  scale: [0.06, 0.13]
  score: 61

Overlord:
  path_to_image: "enemies/src/overlord"
  velocity: 15
  health: 200
  damage: 35
  scale: [0.09, 0.16]
  score: 19

Gremlin:
  path_to_image: "enemies/src/gremlin"
  velocity: 17
  health: 30
  damage: 1
  scale: [0.09, 0.16]
  score: 2

Brute:
  path_to_image: "enemies/src/brute"
  velocity: 17
  health: 50
  damage: 30
  scale: [0.07, 0.16]
  score: 17

Pitbalor:
  path_to_image: "enemies/src/pitbalor"
  velocity: 14
  health: 80
  damage: 40
  scale: [0.09, 0.16]
  score: 37

Stalker:
  path_to_image: "enemies/src/stalker"
  velocity: 16
  health: 290
  damage: 70
  scale: [0.06, 0.15]
  score: 53

Tainted:
  path_to_image: "enemies/src/tainted"
  velocity: 13
  health: 60
  damage: 69
  scale: [0.09, 0.16]
  score: 41
