back_color: "#FFC846"
background_path: "level/src/desert.jpg"
enemies: [Goblin, Imp, Gremlin, Brute, Overlord]
number_of_enemies: 15
font_color: [255, 0, 0]
font_path: "level/src/BleedingPixels.ttf"
font_size: 60

Player:
  angle: 180
  velocity: 20
  weapon: [Shotgun, Minigun]
  max_health: 1500
  sprite_path: "player/src/marine.png"
  scale: [0.07, 0.15]
